### ISSUE TITLE
Include benchmarks on compile speed?

### ISSUE THREAD

**Issue by icefoxen** [bitshifter/mathbench-rs#13]
This may be out of scope for this project but it would be interesting to see how long it takes to compile equivalent code using these various crates. Not sure about the best way to measure though, since rustc's self-benchmarking tools are generally nightly only.

**Comment by bitshifter** [comment]
I'd quite like to do this, it's a useful metric and something I've been
focused on in my own projects. I haven't looked into measuring compile and
link time at all so don't have any ideas on how to do it yet.

**Comment by icefoxen** [comment]
I don't either, to be honest, besides doing `time cargo build` and collecting the results or such.

**Comment by bitshifter** [comment]
Possibly hyperfine would be a good tool for benching compile times, might be overkill though.

**Comment by bitshifter** [comment]
There's also the performance monitoring framework for rust itself that might be good for getting some ideas https://github.com/rust-lang-nursery/rustc-perf

**Comment by bitshifter** [comment]
This nightly feature should do the job, just need to parse the json output

```
cargo +nightly build --release -Z timings=html,info,json
```
