### ISSUE TITLE
Include euclid

### ISSUE THREAD

**Issue by kvark** [bitshifter/mathbench-rs#2]
[euclid](https://github.com/servo/euclid/) is used in Servo and WebRender, has `mint` integration. It would be useful for us (Mozilla graphics team) to see how it fares with other libraries. cc @nical

**Comment by icefoxen** [comment]
I want this too.  Doesn't seem too hard to add, hopefully.

**Comment by bitshifter** [comment]
Sure, I'll take a look.

**Comment by bitshifter** [comment]
Started a branch for this https://github.com/bitshifter/mathbench-rs/tree/euclid

**Comment by bitshifter** [comment]
Merged to master, README has been updated with information on euclid differences and test results.
