### ISSUE TITLE
Add keywords !

### ISSUE THREAD

**Issue by Stargateur** [bitshifter/mathbench-rs#23]
https://doc.rust-lang.org/cargo/reference/manifest.html#the-keywords-field

https://lib.rs/keywords/math

**Comment by bitshifter** [comment]
I can add them although mathbench it's not published as a crate as it's primarily a suite of benchmarks, the lib itself doesn't contain much of use on its own.

**Comment by Stargateur** [comment]
oh sorry I assume it was, https://lib.rs/gh/bitshifter/mathbench-rs/mathbench, lib.rs trick me. (why not publish it actually ?)
