### ISSUE TITLE
Benchmark not using all cores

### ISSUE THREAD

**Issue by utensil** [bitshifter/mathbench-rs#37]
On my mac, benchmarking either `scalar` or `wide` doesn't use all my cores, I wonder if this is expected:

<img width="1062" alt="image" src="https://github.com/user-attachments/assets/fb39c7b3-ceaa-4449-8b3f-db61cf6848f7">

<img width="1073" alt="image" src="https://github.com/user-attachments/assets/b4f71486-daaf-4a51-98a3-a2d6170f80cf">

while compiling has used all my cores to full capacity.

(metrics collected with btop and macmon)

I can't find a configuration to change that in criterion's doc. This won't impact the benchmark result, as they are single-core computations. But using all cores when possible would expedite running the benchmark.

**Comment by bitshifter** [comment]
That is expected, I haven't found anything in Criterion's documentation that suggests that it can do this and even if it did I think it could impact the benchmarks in various ways like the CPU getting hotter and being throttled more or memory bus and/or CPU caches having higher utilization. Micro benchmarks are quite temperamental at the best of times.

**Comment by utensil** [comment]
Thanks for the reply, I also have gone through criterion's docs and issues, but no luck.

Indeed, when not using all cores, it's less likely that the benchmark will be affected by other operations on the computer, and vice versa.

**Comment by bitshifter** [comment]
On my math library glam I had started using [iai-callgrind](https://iai-callgrind.github.io/iai-callgrind/latest/html/benchmarks/overview.html) for benchmarking optimisations that I was making, because it doesn't rely on timing it's quite quick and less variable, but it requires rewriting all of the benchmarks so it's not something I'm likely to do with mathbench.

**Comment by utensil** [comment]
Thank you for the pointer to iai-callgrind, I quickly skim some docs and its [comparison with Criterion](https://iai-callgrind.github.io/iai-callgrind/latest/html/comparison/criterion.html). It's an instruction-based benchmark which is great for performance regression tests in CI, which is similar to [what Lean 4's mathlib uses](http://speed.lean-fro.org/mathlib4/home).

My preliminary plan is to use mathbench's setup to benchmark a different set of libraries on a different set of operations, across CPU and GPU, and even across language (C++, Rust, Zig etc.), which unfortunately needs to measure not only CPU instructions but the time perceived by the callers. I guess I can't use iai-callgrind in that case.
