### ISSUE TITLE
Add a bench result to README

### ISSUE THREAD

**Issue by polarathene** [bitshifter/mathbench-rs#5]
While you should ideally run the bench on your(or intended) system to  see the results, would it still be helpful to have a table of results in the README(or linked from the README)? It would provide some quick/rough insight in what can be expected from the different crates(note the date of the bench and versions of the crates).

**Comment by bitshifter** [comment]
Sure, I have such a table here https://bitshifter.github.io/2019/07/10/introducing-glam-and-mathbench/ but will put a copy in the README.

**Comment by bitshifter** [comment]
Done
