### ISSUE TITLE
How does adding a new lib work?

### ISSUE THREAD

**Issue by Lokathor** [bitshifter/mathbench-rs#6]
It seems like I can just put another row into the list and it magically does it all, and the template seems to be

```rust
.with_function("CRATE NAME", |b| {
            use CRATE::{STUFF};
            bench_unop!(b, op => METHOD_NAME, ty => TYPE)
        })
```

or using `bench_binop` for binary operations

Is this all a person needs to do? Or are there other steps as well?

**Comment by Lokathor** [comment]
Oh it's in the readme but just you gotta scroll waaaay down on a phone, my mistake!

**Comment by bitshifter** [comment]
I only just started adding it to the readme so it probably wasn't there
when you looked. Let me know if you think any documentation is missing.
