### ISSUE TITLE
Dependencies should use an exact patch version

### ISSUE THREAD

**Issue by Lokathor** [bitshifter/mathbench-rs#8]
Since a lib can update its internal formulas for better speed in just a patch release, all dependencies should be listed down to the patch level and benchmark presentations should list the exact version used to run the benchmarks.

**Comment by bitshifter** [comment]
Makes sense. I'm on vacation right now but if you want to make a PR I can merge it. Probably best to use the versions mentioned in the results in the readme if you do.

**Comment by Lokathor** [comment]
I'm working on adding enough to Hektor to get it into the benchmarks, so I'll include patch numbers in that PR if you don't have it set by then.

**Comment by bitshifter** [comment]
You might want to do that against the euclid branch. It's pretty much done, I just need to update the readme before merging to master

**Comment by bitshifter** [comment]
I've made this change on master now.
