### ISSUE TITLE
Dependencies should use their default-features

### ISSUE THREAD

**Issue by Lokathor** [bitshifter/mathbench-rs#9]
Currently all dependencies are set to not use any default features, but most people are probably going to end up including a crate with default features on, so the benchmarks should probably similarly have default features left on.

**Comment by bitshifter** [comment]
This is to reduce compile times, some libraries drag in a lot of dependencies. I'd prefer to enable features that matter for performance than bringing in defaults that don't.

**Comment by bitshifter** [comment]
All libs are now using default features.
